name: deploy to backend

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
    branches:
     - master
  workflow_dispatch:
  
jobs:
    build:
      runs-on: self-hosted
    
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        ECR_REPOSITORY: chat-app
        IMAGE_TAG: latest
           
      steps:
           - name: build and push docker image 
           - uses: actions/checkout@v4
           
           - name: Set up Docker Buildx
             uses: docker/setup-buildx-action@v1

           - name: Login to Amazon ECR
             id: login-ecr
             uses: aws-actions/amazon-ecr-login@v1

           - name: Build and Push Docker image
             id: build-and-push-image
             env:
               ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
               ECR_REPOSITORY: chat-app
               IMAGE_TAG: latest

             run: |
               docker build -t ${{env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
               -f ./backend/Dockerfile ./backend
               docker push ${{env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      

