name: Deploy frontend to aws ec2 server

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
   
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      
      - name: Build the app   
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
          VITE_WS_URL: ${{ secrets.VITE_WS_URL }}
        run: |
          cd frontend
          npm ci
          npm run build 
  

      - name: Rename build folder
        run: mv frontend/dist frontend_build

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Clean Temporary Directory on Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          timeout: 60s
          script: |
            rm -rf ~/deploy-temp
            mkdir -p ~/deploy-temp
            chmod 775 ~/deploy-temp

      - name: Upload Frontend Build to Lightsail
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          source: "frontend_build/*"
          target: "~/deploy-temp"

      - name: Deploy to taa66-frontend folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          script: |
            sudo rm -rf /var/www/html/taa66-frontend
            sudo mkdir -p /var/www/html/taa66-frontend
            sudo cp -r ~/deploy-temp/* /var/www/html/taa66-frontend/
            sudo chmod -R 755 /var/www/html/taa66-frontend
